spring.application.name=gemini_test_try2

server.port=7002

# Gemini API configuration
# google.api.key=AIzaSyB6eW70HMnUzyGp3pzx9XQt7w79nfaXXeA

# google.api.key=AIzaSyC8ssZUaHkCfuYFoB_zpTBAL4wvvJoOpNw

google.api.key=AIzaSyBqyx43u-ObBb9Oq74lK1MEihWqmJDfGFc
